[platformio]
# Indica que el proyecto real está en la subcarpeta
src_dir = voto_electronico_esp32/src
lib_dir = voto_electronico_esp32/lib
include_dir = voto_electronico_esp32/include
test_dir = voto_electronico_esp32/test
data_dir = voto_electronico_esp32/data

# Importa la configuración original
extra_configs = 
    voto_electronico_esp32/platformio.ini